version: '2.2'

services:
  es:
    container_name: elasticsearch
    image: elasticsearch:${TAG}

    volumes: 
     - ${ES_DATA}:/usr/share/elasticsearch/data
     - ${CERTS}:/usr/share/elasticsearch/config/certs

    ports:
      - 9200:9200
      - 9300:9300

    env_file:
      - conf_env

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    cap_add:
      - IPC_LOCK

    healthcheck:
      test: curl --cacert $CERTS/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    container_name: kibana
    image: kibana:${TAG}

    volumes:
      - ${CERTS}:/usr/share/kibana/config/certs
      - ${KIBANA_DATA}:/usr/share/kibana/data

    ports:
      - 5601:5601
        
    env_file:
      - conf_env

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

    depends_on:
      es:
        condition: service_healthy